version: '3.8'
services:
  engine:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - /tmp/order_engine.sock:/tmp/order_engine.sock
    cap_add:
      - SYS_NICE
    environment:
      - CPU_AFFINITY=0
  client:
    image: python:3.9
    volumes:
      - ../scripts:/scripts
      - /tmp/order_engine.sock:/tmp/order_engine.sock
    command: ["python3", "/scripts/order_injector.py"]